name: sqlite2
version: 0.5.0
description: Most recent, fast SQLite bindings for Dart 2.0
homepage: https://github.com/l7ssha/dart-sqlite
authors:
  - Sam McCall
  - P.Y. Laligand
  - Szymon Uglis
environment:
  sdk: '>=1.8.3 <3.0.0'
dependencies:
  http:
  path:
  yaml:
dev_dependencies:
  test:
