name: sqlite2
version: 0.5.1
description: Most recent, fast SQLite bindings for Dart 2.0
homepage: https://github.com/l7ssha/dart-sqlite2
authors:
  - Szymon Uglis <szymon.uglis@tuta.io>
  - Sam McCall
  - P.Y. Laligand
environment:
  sdk: '>=1.8.3 <3.0.0'
dependencies:
  http: any
  path: any
  yaml: any
dev_dependencies:
  test: any
